# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.voice import streaming_voice_pb2 as streaming__voice__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in streaming_voice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamVoiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendVoice = channel.stream_stream(
                '/streaming_voice.StreamVoice/SendVoice',
                request_serializer=streaming__voice__pb2.VoiceRequest.SerializeToString,
                response_deserializer=streaming__voice__pb2.TextReply.FromString,
                _registered_method=True)


class StreamVoiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendVoice(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamVoiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendVoice': grpc.stream_stream_rpc_method_handler(
                    servicer.SendVoice,
                    request_deserializer=streaming__voice__pb2.VoiceRequest.FromString,
                    response_serializer=streaming__voice__pb2.TextReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streaming_voice.StreamVoice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streaming_voice.StreamVoice', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamVoice(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendVoice(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/streaming_voice.StreamVoice/SendVoice',
            streaming__voice__pb2.VoiceRequest.SerializeToString,
            streaming__voice__pb2.TextReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
